name: ci-back-end-workflow
on: 
  pull_requests:
    branches:
      - main
    paths:
      - 'starter/frontkend/**'
  workflow_dispatch:
    inputs:
      trigger-ci:
        description: 'Manually trigger CI'
        required: false
        default: 'false'
jobs:
  ci_be_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
      
      - name: Install Python Dependencies
        run: |
          cd starter/backend
          pipenv install

      - name: Run Lint code
        run: |
          cd starter/backend
          pipenv run lint


  ci_be_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Python
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
      
      - name: Install Python Dependencies
        run: |
          cd starter/backend
          pipenv install

      - name: Run Test code
        run: |
          cd starter/backend
          pipenv run test

  ci_be_build:
    runs-on: ubuntu-latest
    needs: [ci_be_lint, ci_be_test]
    if: ${{ success() && needs.ci_be_lint.result == 'success' && needs.ci_be_test.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Install Python Dependencies
        run: |
          cd starter/backend
          pipenv install
          pipenv run test

      - name: Build application with Docker
        run: |
          docker build \
            --build-arg REACT_APP_MOVIE_API_URL=${{ secrets.MOVIE_API_URL }} \
            -t backend:${{ github.sha }} .
