name: ci-back-end-workflow
on: 
  pull_requests:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:
    inputs:
      trigger-ci:
        description: 'Manually trigger CI'
        required: false
        default: 'false'
jobs:
  ci_be_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Lint code
        run: |
          cd starter/frontend
          npm install
          npm run lint

  ci_be_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Test code
        run: |
          cd starter/frontend
          npm install
          npm test

  ci_be_build:
    runs-on: ubuntu-latest
    needs: [ci_be_lint, ci_be_test]
    if: ${{ success() && needs.ci_be_lint.result == 'success' && needs.ci_be_test.result == 'success' }}
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Build code
        run: |
          cd starter/frontend
          npm install
          npm run build
    
