name: cd-front-end
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  cd_fe_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Test code
        run: |
          cd starter/frontend
          npm install
          npm test

  cd_fe_build:
    runs-on: ubuntu-latest
    needs: cd_fe_test
    if: ${{ success() && needs.cd_fe_lint.result == 'success' && needs.cd_fe_test.result == 'success' }}
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Build code
        run: |
          cd starter/frontend
          npm install
          npm run build
    
