name: hello-world-ci-front-end
on:
  # pull_requests:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  ci_fe_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Lint code
        run: |
          cd starter/frontend
          npm install
          npm run lint

  ci_fe_test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Test code
        run: |
          cd starter/frontend
          npm test

  ci_fe_build:
    runs-on: ubuntu-latest
    needs: [ci_fe_lint, ci_fe_test]
    if: ${{ success() && needs.ci_fe_lint.result == 'success' && needs.ci_fe_test.result == 'success' }}
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Build code
        run: |
          cd starter/frontend
          npm run build


    
