name: cd-front-end-workflow
on: 
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  cd_fe_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json
      
      - name: Install Dependencies
        run: npm ci
        working-directory: starter/frontend

      - name: Run Lint code
        run: npm run lint
        working-directory: starter/frontend


  cd_fe_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json
      
      - name: Install Dependencies
        run: npm ci
        working-directory: starter/frontend

      - name: Run Test code
        run: npm run test
        working-directory: starter/frontend

  cd_fe_build:
    runs-on: ubuntu-latest
    needs: [cd_fe_test, cd_fe_lint]
    if: ${{ success() && needs.cd_fe_lint.result == 'success' && needs.cd_fe_test.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: starter/frontend/package-lock.json
        
      - name: Install depends
        run: npm install
        working-directory: starter/frontend

      - name: Testing
        run: npm run test
        working-directory: starter/frontend
  
  cd_fe_deploy:
    runs-on: ubuntu-latest
    needs: [cd_fe_build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ AWS_DEFAULT_REGION }}
      
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ AWS_ACCOUNT_ID }}.dkr.ecr.${{ AWS_DEFAULT_REGION }}.amazonaws.com/frontend
          tags: |
            type=sha 
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: starter/frontend
          tag_with_sha: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            REACT_APP_MOVIE_API_URL=${{ vars.REACT_APP_MOVIE_API_URL }}
      
      - name: Update Kubeconfig K8S cluster
        run: aws eks update-kubeconfig --name cluster --region ${{ AWS_DEFAULT_REGION }}

      - name: Deploy Frontend application to EKS cluster
        run: |
          kustomize edit set image frontend=${{ steps.meta.outputs.tags }}
          kustomize build | kubectl apply -f -
        working-directory: starter/frontend/k8s